document.writeln("<center>")
document.writeln("<hr width=600 color=black")
document.writeln("<h1>INSTITUT BISNINS INFORMATIKA KESATUAN</h1>")
document.writeln("<h2>FAKULTAS INFORMATKA DAN PARIWISATA</h2>")
document.writeln("<h3>JURUSAN TEKNOLOGI INFORMASI</h3>")
document.writeln("<hr width = 600 color=black>")
document.writeln("</center>")